### PR TITLE
Fix issues with dropEnabled for container that becomes empty

### PR DESCRIPTION
**Pull request by apaan**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
  Bug fix
- **What is the current behavior?** (You can also link to an open issue here)
  #70
- **Other information**:

If a container that had element(s) became empty, any element won't be able to be dropped to the container, because dropEnabled stays false.

This commit fixes by changing dropEnabled if the data of the container becomes empty. To do that in minimal invasion to existing code, we can use Object.observe or Proxy. Because Object.observe is deprecated, and Proxy is not supported in IE, we have to change DragDropSortableService. From only containing the array (sortableData), DragDropSortableService now contains the container (csortableContainer).

### CODE REVIEW

**Comment by apaan** [comment]
sorry, i didn't see that the files are changed in last commits. I will update this.

**Comment by cire09** [comment]
Hi guys. When will this be finally be part of ng2-dnd?

**Comment by scot1289** [comment]
Seems to still be an issue. I don't see any of the changes you made for 713c1b6
Is there a reason why you have within the SortableContainer class?
`this.dropEnabled = this._sortableData.length === 0;`

That seems to be causing the issue.

**Comment by akserg** [comment]
Hi @apaan ,

Thank you for PR.

**Pull request merged**
