### PR TITLE
Adding angular4 as a peer dependency.

### PR DESCRIPTION
**Pull request by vangorra**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Adds support for angular ^4.0.0

### CODE REVIEW

**Comment by vangorra** [comment]
It will work but npm will warn about a peer dependency missing. If you use npm shrinkwrap, it won't work at all without the peer dependency being set.

**Comment by morocarlo** [comment]
can you merge and release this  branch on production?

**Comment by akserg** [comment]
Today evening.

**Comment by akserg** [comment]
Hi @vangorra 

I made merge via command line into the new repo and run `npm install`. The installed version of Angular was 2.4.10, so the bundle's build was based on it. 

Can you explain how can I use version `^4.0.0` from the given semver range in `"@angular/core": "^2.4.4 || ^4.0.0"`? 
I have only one idea - update all `@angular/...` dependencies to version `^4.0.0` such that `"@angular/core": "^4.0.0"` and etc.

**Comment by vangorra** [comment]
@akserg I'm not entirely sure what error you are mentioning. The benefit to this pull request comes when your project makes use of `npm shrinkwrap`. Shrinkwrapping locks dependency versions in place, so your build and app will behave predictably even when a dependency introduces a bug in a later minor version.

I have setup some examples that demonstrate how this change will help an angular 4 project.
https://github.com/vangorra/ng2-dnd-examples

The examples demonstrate the following:
- ng2 - angular 2 application with ng2-dnd where npm shrinkwrap has been used successfully.
- ng4-with-errors - angular 4 application with ng2-dnd where npm shrinkwrap cannot be used as there are errors about peer dependencies.
- ng4 - angular 4 application with with ng2-dnd (and this pull request) where npm shrinkwrap has been used successfully.

**Comment by trik** [comment]
since the development of this module is stuck at 30th of january and i really needed it for my ng4 project, i published an update on my fork (ng4 update and es5/es2015/umd bundles generation). the modified version is available on npm as ngx-dnd. if anyone interested, feel free to contribute

**Comment by akserg** [comment]
Done.

**Pull request merged**
