### PR TITLE
drop fix

### PR DESCRIPTION
**Pull request by bjovanovic84**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix for issue #184 

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

### CODE REVIEW

**Comment by thepauleh** [comment]
like this change, looking forward to seeing it published 👍

**Comment by projetkourou** [comment]
That's great . Any news about when this will be accept & merge in master ?

**Comment by okahn** [comment]
Works great! Will this be merged soon?

**Comment by akserg** [comment]
Hi, @bjovanovic84 

Thank you for PR.

**Pull request merged**
