### PR TITLE
Use sortable component with FormArray also

### PR DESCRIPTION
**Pull request by loudandwicked**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
A feature

* **What is the current behavior?** (You can also link to an open issue here)
Currently sortable component only works on arrays.

* **What is the new behavior (if this is a feature change)?**
This one adds a feature to use it with Reactive Forms' FormArray.

* **Other information**:
This one still needs tests to be written for FormArray, tests for current behavior (arrays) are passing.

Is this something you'd include into this project? If so, I can finish work on this.

### CODE REVIEW

**Comment by akserg** [comment]
Hi @loudandwicked 

Can you, please update the README with example demonstrates the usage of DnD in FormArray?

**Comment by loudandwicked** [comment]
It actually works on FormArray exactly the same as on Array. Do you think README needs an example of that, or would just mentioning that you can also use FormArray instead of Array be sufficient?

**Comment by akserg** [comment]
> It actually works on FormArray exactly the same as on Array. 

Yes, I get it

> Do you think README needs an example of that, or would just mentioning that you can also use FormArray instead of Array be sufficient?

The working code snippet with short explanation in README would be a good advantage because no one shows the example of DnD between form elements.

P.S. Please add your name to the list of contributors at the bottom of README.

**Comment by loudandwicked** [comment]
I have added an example to README and also added my name to contributors in this last commit.

**Comment by justinlettau** [comment]
Any ETA on getting this released? I would like to use `ng2-dnd` but need this feature. Thanks.

**Comment by lucaube** [comment]
@justinlettau What justin said. Any ETA? I would like this feature.

**Comment by edcarroll** [comment]
@justinlettau, @lucaube, if you'd like to use this now in your project, I've forked and merged this PR and published to npm as `@edcarroll/ng2-dnd`. Feel free to install this at your leisure until this is merged.

It contains the less restrictive `package.json` support (Angular ^2.4 || >=4.0.0). One other minor change is that when sorting the form array it updates the dirty state automatically.

**Comment by lucaube** [comment]
@edcarroll  Thank you. I will give it a shot. I really hated the fact that I had to create custom validation for lists of objects instead of using the reactive forms.

**Comment by benlegault** [comment]
Hi I would like to know if this has been resolved and available in the current branch?  It doesn't seem to work for me.  I do not have any error, the display order change but not in the formArray.  I've followed the example in the readme file but...no luck

**Comment by jessycormier** [comment]
@benlegault if you look at @edcarroll comment, you can see a new fork was created that holds this solution. Until the conflicts are resolved the formArray will not work on this repository.

**Comment by benlegault** [comment]
Thanks @jessycormier for the quick response. @edcarroll I tried your package also but I have the same issue.  Is there something specific that needs to be done "different" from what has been specified here?

**Comment by edcarroll** [comment]
@benlegault make sure you're passing in the form array instance itself, not the array property of the form array. Hopefully that should be it

**Comment by akserg** [comment]
Hi @loudandwicked 

Thank you for PR.

**Pull request merged**
